name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: |
        echo "Memulai training model SVM..."
        python train.py
    
    - name: Test model
      run: |
        echo "Testing model..."
        python test.py
    
    - name: Check accuracy
      run: |
        ACCURACY=$(cat accuracy.txt)
        echo "Model accuracy: $ACCURACY"
        
        python -c "
        accuracy = float(open('accuracy.txt').read())
        if accuracy > 0.7:
            print('Model performance: BAIK (> 70%)')
        elif accuracy > 0.5:
            print('Model performance: CUKUP (> 50%)')
        else:
            print('Model performance: KURANG (< 50%)')
            exit(1)
        "
    
    - name: Save model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: |
          model.pkl
          accuracy.txt
    
    - name: Show results
      run: |
        echo "Training dan testing selesai!"
        echo "Accuracy: $(cat accuracy.txt)"
