name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t mlops-model -f docker/Dockerfile.model .

    - name: Run training in Docker
      run: docker run --rm -v "${{ github.workspace }}/model:/app/model" -v "${{ github.workspace }}/iris_dataset.csv:/app/model/iris_dataset.csv" mlops-model

    - name: Test model
      run: docker run --rm -v "${{ github.workspace }}/model:/app/model" mlops-model python test.py > accuracy.txt

    - name: Check accuracy
      run: |
        ACCURACY=$(cat accuracy.txt)
        echo "Model accuracy: $ACCURACY"
        
        python -c "
        accuracy = float(open('accuracy.txt').read())
        if accuracy > 0.7:
            print('Model performance: BAIK (> 70%)')
        elif accuracy > 0.5:
            print('Model performance: CUKUP (> 50%)')
        else:
            print('Model performance: KURANG (< 50%)')
            exit(1)
        "
    
    - name: Save model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: |
          model.pkl
          accuracy.txt
    
    - name: Show results
      run: |
        echo "Training dan testing selesai!"
        echo "Accuracy: $(cat accuracy.txt)"
